name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Rust Code Coverage
      # You may pin to the exact commit or the version.
      # uses: Swatinem/fucov@304910a1829c88889a0b5671aa5ca7b1abbeebc0
      uses: Swatinem/fucov@v1.0.0
      with:
        # The desired output format. One of `lcov`, `json`, `html` or `profdata`. Defaults to `lcov`.
        output-format: lcov
    - name: Codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378
      uses: codecov/codecov-action@v3.1.0
      with:
        # Repository upload token - get it from codecov.io. Required only for private repositories
        # token: # optional
        # Specify whether the Codecov output should be verbose
        verbose: true
